spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/restaurant
          jwk-set-uri: http://localhost:8180/realms/restaurant/protocol/openid-connect/certs

server:
  port: 8080
